Onboard Debug LEDs
Routines for controlling the onboard Debug LEDs.
Functions
int set_led (char led)
int clear_led (char led)
int toggle_led (char led)
void led_pwm_fade (void)
Detailed Description
Routines for controlling the onboard Debug LEDs.
 #include <leds.h> 
This Routines are for setting, clearing and toggeling the four onboard LEDs
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006
Author: Rainer Ostendorf
Function Documentation
int clear_led (char led)
turn off the given led
Parameters:
led number of the led to turn off (0-3)
Returns: -1 if led has illegal value, 0 else
Definition at line 57 of file leds.c.
void led_pwm_fade (void)
led the leds 1 and 3 fade in and out. BEWARE: this functions uses busy waiting and wastes a huge amount of cpu-time!
Definition at line 84 of file leds.c.
References delay_ms(), and toggle_led().
int set_led (char led)
turn on the given led
Parameters:
led number of the led to turn on (0-3)
Returns: -1 if led has illegal value, 0 else
Definition at line 43 of file leds.c.
Referenced by main().
int toggle_led (char led)
toggle the given led
Parameters:
led number of the led to toggle (0-3)
Returns: -1 if led has illegal value, 0 else
Definition at line 70 of file leds.c.
Referenced by led_pwm_fade().