Serial Monitor
A serial debug monitor.
Defines
#define BUFLEN 32
Functions
void monitor ()
Detailed Description
A serial debug monitor.
 #include <monitor.h> 
The monitor program shows internal system-parameter and allows manipulations of variables
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006
Author: Rainer Ostendorf
Define Documentation
#define BUFLEN 32
Definition at line 49 of file monitor.h.
Referenced by monitor().
Function Documentation
void monitor ()
Definition at line 43 of file monitor.c.
References __motor1_duty, __motor2_duty, accl_high_samples, accl_low_samples, adc_sel_channel(), BUFLEN, gyro1_samples, GYRO1_SAMPLES_BUFSIZE, gyro1_temp, gyro2_samples, gyro2_temp, PWM_RESOLUTION, read_adc(), SYS_CLK, uart_puts(), and uart_puts_P.