Motor PWM
Routines for controlling PWM-Signals towards the Motors.
Defines
#define PWM_RESOLUTION 255
#define PWM_SECURITY_MAX_FREQ 10000
#define PWM_SECURITY_MIN_DUTY (PWM_RESOLUTION / 200)
Functions
void init_motor_pwm (void)
void set_motor_pwm_freq (uint16_t hz)
void enable_motor1 (void)
void enable_motor2 (void)
void disable_motor1 (void)
void disable_motor2 (void)
void set_motor1 (uint8_t speed, uint8_t dir)
void set_motor2 (uint8_t speed, uint8_t dir)
Variables
uint8_t __motor1_duty
uint8_t __motor2_duty
Detailed Description
Routines for controlling PWM-Signals towards the Motors.
 #include <motor_pwm.h> 
This Routines are for setting the PWMs base frequency and for scaling the modulated duty cycle.
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006
Author: Rainer Ostendorf
Define Documentation
#define PWM_RESOLUTION 255
Definition at line 68 of file motor_pwm.h.
Referenced by monitor(), set_motor1(), set_motor2(), set_motor_pwm_freq(), and stabilizer_loop().
#define PWM_SECURITY_MAX_FREQ 10000
Definition at line 76 of file motor_pwm.h.
Referenced by set_motor_pwm_freq().
#define PWM_SECURITY_MIN_DUTY (PWM_RESOLUTION / 200)
Definition at line 83 of file motor_pwm.h.
Referenced by set_motor1(), and set_motor2().
Function Documentation
void disable_motor1 (void) [inline]
set enable-signal of motor 1 to low
Definition at line 110 of file motor_pwm.c.
Referenced by main().
void disable_motor2 (void) [inline]
set enable-signal of motor 2 to low
Definition at line 120 of file motor_pwm.c.
Referenced by main().
void enable_motor1 (void) [inline]
set enable-signal of motor 1 to high
Definition at line 115 of file motor_pwm.c.
void enable_motor2 (void) [inline]
set enable-signal of motor 2 to high
Definition at line 125 of file motor_pwm.c.
void init_motor_pwm (void)
Initialize the PWM-Signal generation for the both motors
Definition at line 55 of file motor_pwm.c.
Referenced by main().
void set_motor1 (uint8_t speed, uint8_t dir) [inline]
Set the duty-cycle of motor 1
Parameters:
speed Percentage of duty (high) level during clock cycle the maximum speed is PWM_RESOLUTION (typlicalle 255), the minimum speed is 0.
dir Direction of the motor. Either 0(forward) or 1(backward)
Definition at line 130 of file motor_pwm.c.
References __motor1_duty, PWM_RESOLUTION, and PWM_SECURITY_MIN_DUTY.
Referenced by main(), and stabilizer_loop().
void set_motor2 (uint8_t speed, uint8_t dir) [inline]
Set the duty-cycle of motor 2
Parameters:
speed Percentage of duty (high) level during clock cycle the maximum speed is PWM_RESOLUTION (typlicalle 255), the minimum speed is 0.
dir Direction of the motor. Either 0 (forward) or 1(backward)
Definition at line 149 of file motor_pwm.c.
References __motor2_duty, PWM_RESOLUTION, and PWM_SECURITY_MIN_DUTY.
Referenced by main(), and stabilizer_loop().
void set_motor_pwm_freq (uint16_t hz)
Set the base frequency for the PWM signal
Parameters:
hz frequency in Hertz
Definition at line 99 of file motor_pwm.c.
References __motor1_duty, __motor2_duty, PWM_RESOLUTION, PWM_SECURITY_MAX_FREQ, and SYS_CLK.
Referenced by main().
Variable Documentation
uint8_t __motor1_duty
Please dont touch these values, as they are used by the set_pwm_frequency-method to adjust the theshold (OCRx) values, after a update to the TOP-value (ICP) of the counter was performed
Definition at line 90 of file motor_pwm.h.
Referenced by monitor(), set_motor1(), and set_motor_pwm_freq().
uint8_t __motor2_duty
Definition at line 91 of file motor_pwm.h.
Referenced by monitor(), set_motor2(), and set_motor_pwm_freq().