SPI for Gyros
Code for accessing the Gyroscopes.
Defines
#define CS_GYRO1 0
#define CS_GYRO2 2
#define ACC_HB 0x83
#define ACC_LB 0x00
#define TEMP_HB 0x87
#define TEMP_LB 0x00
Typedefs
typedef enum gyro_fsm_state_enum gyro_fsm_state
Enumerations
enum gyro_fsm_state_enum {
first_run,
g1_hacc,
g1_lacc,
g2_hacc,
g2_lacc,
g1_htmp,
g1_ltmp,
g2_htmp,
g2_ltmp
 }
Functions
void init_spi_gyro (uint8_t interrupt_mode)
void spi_cs (uint8_t chip)
uint8_t spi_write_8 (uint8_t data)
Transfer 1 Byte given in data via the SPI return the 1 Byte sampled during transfer.
uint8_t spi_write_8_nocs (uint8_t data)
uint16_t spi_write_16 (uint16_t data)
Tranfer 2 Bytes given in data via the SPI, return the 2 Bytes sampled during transfer.
uint16_t spi_write_16_nocs (uint16_t data)
Variables
gyro_fsm_state gyro_state
Detailed Description
Code for accessing the Gyroscopes.
 #include <gyro_spi.h> 
These are the functions for initializing and using the SPI- Interface. Please be aware, that the Code currently is optimized for use with the Gyroscopes. One will need to modify it for reusing with other purpose.
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006
Author: Rainer Ostendorf
Define Documentation
#define ACC_HB 0x83
high-byte of `read acceleration` control word for ADIS16100
Definition at line 88 of file gyro_spi.h.
Referenced by SIGNAL().
#define ACC_LB 0x00
low-byte of `read acceleration` control word for ADIS16100 -> 2's complement
Definition at line 90 of file gyro_spi.h.
Referenced by SIGNAL().
#define CS_GYRO1 0
chipselect for gyro1
Definition at line 82 of file gyro_spi.h.
#define CS_GYRO2 2
chipselect for gyro2
Definition at line 84 of file gyro_spi.h.
Referenced by SIGNAL().
#define TEMP_HB 0x87
high-byte of `read tempereature` control word for ADIS16100
Definition at line 93 of file gyro_spi.h.
Referenced by SIGNAL().
#define TEMP_LB 0x00
low-byte of `read tempereature` control word for ADIS16100
Definition at line 95 of file gyro_spi.h.
Referenced by SIGNAL().
Typedef Documentation
typedef enum gyro_fsm_state_enum gyro_fsm_state
state definition for the finite state maschine running inside the SPI-ISR
Enumeration Type Documentation
enum gyro_fsm_state_enum
state definition for the finite state maschine running inside the SPI-ISR
Enumerator:
first_run
 first run of the ISR, not initialized
g1_hacc
 high-byte of `read-acceleration` word was send to gyro 1
g1_lacc
 low-byte of `read-acceleration` word was send to gyro 1
g2_hacc
 high-byte of `read-acceleration` word was send to gyro 2
g2_lacc
 low-byte of `read-acceleration` word was send to gyro1
g1_htmp
 high-byte of `read-temperature` word was send to gyro1
g1_ltmp
 low-byte of `read-temperature` word was send to gyro1
g2_htmp
 high-byte of `read-temperature` word was send to gyro2
g2_ltmp
 high-byte of `read-temperature` word was send to gyro2
Definition at line 98 of file gyro_spi.h.
Function Documentation
void init_spi_gyro (uint8_t interrupt_mode)
Initialize the onboard SPInterface to match the needs of the AD ADIS16100 Gyroskope. This means setting the clock, setting the ports directions, setting mode etc.
Parameters:
interrupt_mode flag wether to enable the interrupt mode in irq-mode, the ISR takes care of reading the Gyros as fast as possible and fills a global array used as ringbuffer of sample-values. Either the Gyros have to be read manually by calling the spi_write-functions.
Set the SPI-port-Pin directions: B0 - /SS -> Output, 1 B1 - SCLK -> Output, 1 B2 - MOSI -> Output, 1 B3 - MISO -> Input, 0
Set SPI Control register: 7 - SPIE, Interrup Enable -> 1, enable IRQs 6 - SPE, SPI-Enbale -> 1, enable SPI-System 5 - DORD, DataOrder -> 0, MSB first (leftshift) 4 - MSTR, Master/Slave -> 1, MasterMode 3 - CPOL, ClkPolarity -> 0, begin with leading edge rising,trailing edge falling 2 - CPHA, ClkPhase -> 1, sample on leading edge (0-1), setup on trailing(1-0) 1,0 SPR1,0, ClockRate, 1,1 - for 125 kHz CLK with SPI2x not set
Set SPI Status Register: 0, SPI2X -> 1,clk-doubling for 0.25 Mhz
Set the selftest-signals to be outputs
deactive self-tests
Definition at line 183 of file gyro_spi.c.
void spi_cs (uint8_t chip)
choose a chip by setting the CS1 and CS2 signal towards the GAL according
Parameters:
chip Nr of the /CS-Signal to choose (0-3)
Definition at line 239 of file gyro_spi.c.
Referenced by read_from_ram(), read_from_spi(), write_to_ram(), and write_to_spi().
uint16_t spi_write_16 (uint16_t data)
Tranfer 2 Bytes given in data via the SPI, return the 2 Bytes sampled during transfer.
Parameters:
data 16bit word that is transferred
Returns: data sampled during transfer
Definition at line 298 of file gyro_spi.c.
uint16_t spi_write_16_nocs (uint16_t data)
Definition at line 329 of file gyro_spi.c.
Referenced by read_from_ram(), read_from_spi(), write_to_ram(), and write_to_spi().
uint8_t spi_write_8 (uint8_t data)
Transfer 1 Byte given in data via the SPI return the 1 Byte sampled during transfer.
Parameters:
data 8bit word that is transferred
Returns: data sampled during transfer
Definition at line 252 of file gyro_spi.c.
uint8_t spi_write_8_nocs (uint8_t data)
Definition at line 277 of file gyro_spi.c.
Referenced by read_from_ram(), read_from_spi(), write_to_ram(), and write_to_spi().
Variable Documentation
gyro_fsm_state gyro_state
the state variable for the ISRs finite state maschine
Definition at line 120 of file gyro_spi.h.
Referenced by SIGNAL().