2.4 GHz Transceiver MAC layer
MAC layer code for the MC13192 2.4GHz Transceiver.
Defines
#define MC13192_IDLE 0
#define MC13192_RX 1
#define MC13192_TX 2
#define NO_PACKET 0
#define RX_PACKET 1
#define TX_PACKET 2
#define DROP_PACKET 3
Functions
void MC13192_init ()
Initialize the MC13192 TODO: write detailed code description!
void init_rx_pkt_mode (void)
switch MC13192 to receive mode TODO: write detailed code description!
int get_rx_pkt (rx_packet_t *rx_packet)
read a data paket from MC13192
void MC13192_update_state (void)
Update the state variable to reflect the state of MC13192.
int tx_pkt_mode (tx_packet_t *tx_packet)
send a data packet TODO: write detailed code description!
void cca_modus (void)
Variables
uint8_t mc13192_mode
uint8_t mc13192_state
Detailed Description
MAC layer code for the MC13192 2.4GHz Transceiver.
 #include <helpers.h> 
This contains functions for intializing the chip and switching its internal states and modes of operation
Author: Original by Dennis Meiering 2004, ported to AVR by Rainer Ostendorf 2006
Define Documentation
#define DROP_PACKET 3
Definition at line 53 of file transceiver_mac.h.
Referenced by MC13192_update_state().
#define MC13192_IDLE 0
Definition at line 46 of file transceiver_mac.h.
Referenced by MC13192_init().
#define MC13192_RX 1
Definition at line 47 of file transceiver_mac.h.
#define MC13192_TX 2
Definition at line 48 of file transceiver_mac.h.
#define NO_PACKET 0
Definition at line 50 of file transceiver_mac.h.
Referenced by MC13192_init(), and MC13192_update_state().
#define RX_PACKET 1
Definition at line 51 of file transceiver_mac.h.
Referenced by MC13192_update_state().
#define TX_PACKET 2
Definition at line 52 of file transceiver_mac.h.
Referenced by MC13192_update_state().
Function Documentation
void cca_modus (void)
Definition at line 84 of file transceiver_mac.c.
References read_from_spi(), uart_puts(), and write_to_spi().
int get_rx_pkt (rx_packet_t * rx_packet)
read a data paket from MC13192
r
TODO: write detailed code description!
Parameters:
rx_packet Datastructure to save the received data to
Returns: 1 in every case
Definition at line 122 of file transceiver_mac.c.
References rx_packet_t::dataLength, read_from_ram(), and read_from_spi().
void init_rx_pkt_mode (void)
switch MC13192 to receive mode TODO: write detailed code description!
Definition at line 116 of file transceiver_mac.c.
References write_to_spi().
void MC13192_init ()
Initialize the MC13192 TODO: write detailed code description!
Definition at line 36 of file transceiver_mac.c.
References MC13192_IDLE, mc13192_mode, mc13192_state, NO_PACKET, read_from_spi(), and write_to_spi().
Referenced by main().
void MC13192_update_state (void)
Update the state variable to reflect the state of MC13192.
* TODO: write detailed code description!
Definition at line 59 of file transceiver_mac.c.
References DROP_PACKET, mc13192_state, NO_PACKET, read_from_spi(), RX_PACKET, and TX_PACKET.
int tx_pkt_mode (tx_packet_t * tx_packet)
send a data packet TODO: write detailed code description!
Parameters:
tx_packet
Definition at line 132 of file transceiver_mac.c.
References tx_packet_t::dataLength, write_to_ram(), and write_to_spi().
Variable Documentation
uint8_t mc13192_mode
Definition at line 33 of file transceiver_mac.c.
Referenced by MC13192_init().
uint8_t mc13192_state
Definition at line 34 of file transceiver_mac.c.
Referenced by MC13192_init(), and MC13192_update_state().