2.4 GHz Transceiver SPI Interface
Routines for accessing the Freescale MC13192 2.4GHz Transceiver.
Data Structures
struct tx_packet_t
struct rx_packet_t
Defines
#define TRANSCEIVER_CS 2
Functions
void write_to_spi (uint8_t spi_adress, uint16_t spi_data)
void write_to_ram (uint8_t spi_adress, tx_packet_t *tx_packet)
uint8_t read_from_spi (uint8_t spi_addr)
uint8_t read_from_ram (uint8_t spi_adress, rx_packet_t *rx_packet)
Detailed Description
Routines for accessing the Freescale MC13192 2.4GHz Transceiver.
 #include <transceiver_spi.h> 
This Routines are for reading and writing to the 802.14.1 Transceiver using the SPI interface
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006 and on the Freescale reference manual v1.5, 10/2005 for MC13192
Author: Rainer Ostendorf
Define Documentation
#define TRANSCEIVER_CS 2
Definition at line 49 of file transceiver_spi.h.
Referenced by read_from_ram(), read_from_spi(), write_to_ram(), and write_to_spi().
Function Documentation
uint8_t read_from_ram (uint8_t spi_adress, rx_packet_t * rx_packet)
Definition at line 70 of file transceiver_spi.c.
References rx_packet_t::dataLength, rx_packet_t::datan, spi_cs(), spi_write_16_nocs(), spi_write_8_nocs(), and TRANSCEIVER_CS.
Referenced by get_rx_pkt().
uint8_t read_from_spi (uint8_t spi_addr)
Definition at line 41 of file transceiver_spi.c.
References spi_cs(), spi_write_16_nocs(), spi_write_8_nocs(), and TRANSCEIVER_CS.
Referenced by cca_modus(), get_rx_pkt(), MC13192_init(), and MC13192_update_state().
void write_to_ram (uint8_t spi_adress, tx_packet_t * tx_packet)
Definition at line 53 of file transceiver_spi.c.
References tx_packet_t::dataLength, tx_packet_t::datan, spi_cs(), spi_write_16_nocs(), spi_write_8_nocs(), and TRANSCEIVER_CS.
Referenced by tx_pkt_mode().
void write_to_spi (uint8_t spi_adress, uint16_t spi_data)
Definition at line 31 of file transceiver_spi.c.
References spi_cs(), spi_write_16_nocs(), spi_write_8_nocs(), and TRANSCEIVER_CS.
Referenced by cca_modus(), init_rx_pkt_mode(), MC13192_init(), and tx_pkt_mode().