ADC Routines
Routines for controlling the onboard Analog-Digital converter.
Defines
#define ADC_GYRO1 0
#define ADC_GYRO2 1
#define ADC_CH2 2
#define ADC_CH3 3
#define ADC_STEERING_1 4
#define ADC_STEERING_2 5
#define ADC_TACHO_1 6
#define ADC_TACHO_2 7
Functions
void init_adc ()
void adc_sel_channel (char channel)
unsigned int read_adc ()
void print_all_adc (void)
Detailed Description
Routines for controlling the onboard Analog-Digital converter.
 #include <adc.h> 
This Routines are for initializing the ADC and selecting the analog input channel of the multiplexer. After a channel has be activated, a single conversion may be performed by calling read_adc().
Note: Based on Atmel Datasheet for Atmega128, Nov. 2006
Author: Rainer Ostendorf
Define Documentation
#define ADC_CH2 2
2: current unused, pin header
Definition at line 67 of file adc.h.
#define ADC_CH3 3
3: current unused, pin header
Definition at line 69 of file adc.h.
#define ADC_GYRO1 0
the ADC-channels : 0: connected to Vref of Gyro 1
Definition at line 63 of file adc.h.
#define ADC_GYRO2 1
1: connected to Vref of Gyro 2
Definition at line 65 of file adc.h.
#define ADC_STEERING_1 4
4: steering potetiometer, X-Axis
Definition at line 71 of file adc.h.
Referenced by stabilizer_loop().
#define ADC_STEERING_2 5
5: steering potetiometer, Y-Axis
Definition at line 73 of file adc.h.
#define ADC_TACHO_1 6
6: Tacho 1, (to be defined)
Definition at line 75 of file adc.h.
#define ADC_TACHO_2 7
7: Tacho 2 (to be defined)
Definition at line 77 of file adc.h.
Function Documentation
void adc_sel_channel (char channel)
select the active ADC-Channel from input multiplexer
Parameters:
channel ADC-Channel to read, 0-7
Definition at line 71 of file adc.c.
Referenced by monitor(), print_all_adc(), and stabilizer_loop().
void init_adc ()
Definition at line 46 of file adc.c.
Referenced by main().
void print_all_adc (void)
demo-code: read in all ADC channels and print their result to the first uart.
Definition at line 94 of file adc.c.
References adc_sel_channel(), read_adc(), and uart_puts().
unsigned int read_adc ()
start an ADConversion, busy-wait for the result and return it a conversion will last approx. 12us (calculated, not measured, TODO)
Returns: the conversion result
Definition at line 81 of file adc.c.
Referenced by monitor(), print_all_adc(), and stabilizer_loop().