main.h File Reference
#define SYS_CLK 16000000
int main (void)
Define Documentation
#define SYS_CLK 16000000
Definition at line 36 of file main.h.
Referenced by monitor(), and set_motor_pwm_freq().
Function Documentation
int main (void)
Definition at line 163 of file main.c.
References disable_motor1(), disable_motor2(), init_accel_capture(), init_adc(), init_irled_pwm(), init_motor_pwm(), init_port_directions(), init_port_values(), init_uart(), MC13192_init(), print_status(), set_led(), set_motor1(), set_motor2(), set_motor_pwm_freq(), and uart_puts_P.