main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/pgmspace.h>
#include `main.h`
#include `gpio.h`
#include `helpers.h`
#include `uart.h`
#include `leds.h`
#include `motor_pwm.h`
#include `adc.h`
#include `gyro_spi.h`
#include `accel_capture.h`
#include `globals.h`
#include `monitor.h`
#include `irled_pwm.h`
#include `stabilizer.h`
#include `transceiver_mac.h`
Functions
void print_status ()
int main (void)
Variables
const unsigned char random_array [1024]
Function Documentation
int main (void)
Definition at line 163 of file main.c.
References disable_motor1(), disable_motor2(), init_accel_capture(), init_adc(), init_irled_pwm(), init_motor_pwm(), init_port_directions(), init_port_values(), init_uart(), MC13192_init(), print_status(), set_led(), set_motor1(), set_motor2(), set_motor_pwm_freq(), and uart_puts_P.
void print_status ()
Definition at line 156 of file main.c.
References uart1_puts_P, and uart_puts_P.
Referenced by main().
Variable Documentation
const unsigned char random_array[1024]
Definition at line 100 of file main.c.