stabilizer.h File Reference
Defines
#define PI 3.14
#define GYRO1_ZERO_VALUE -65.0
#define GYRO_TO_OMEGA_FACTOR 0.002556634
#define ACCL_TO_DEGREE_FACTOR 25.0
#define STEERING_ZERO_POINT 512
#define STEERING_RESPONSIVENESS 0.001
#define K_ANGLE 5.0
#define K_OMEGA 0.16666
#define K_CORR_FACTOR 1.0
#define SET_POINT 0.0
#define CUR_SPEED_FACTOR 4.0
Functions
void stabilizer_loop (void)
Define Documentation
#define ACCL_TO_DEGREE_FACTOR 25.0
correction factor for scaling the acclerometer value to degrees
Definition at line 72 of file stabilizer.h.
Referenced by stabilizer_loop().
#define CUR_SPEED_FACTOR 4.0
factor to scale the set value with for current speed TODO: Check comment! Add detailed desciption
Definition at line 104 of file stabilizer.h.
Referenced by stabilizer_loop().
#define GYRO1_ZERO_VALUE -65.0
the initial value, the gyroscope 1 measures, when not beeing moved
Definition at line 55 of file stabilizer.h.
Referenced by stabilizer_loop().
#define GYRO_TO_OMEGA_FACTOR 0.002556634
scaling factor to calculate the angular speed (omega) from the Gyroscope1 value
from orignal code : OMEGA = (((GYRO-GYRO_zero) / 2048) * 2 * PI * 300) / 360; <=> OMEGA = ((GYRO-GYRO_zero) * 0.920388) / 360 <=> OMEGA = ((GYRO-GYRO_zero) * 2.556634E-3
TODO: Needs to be adapted to sensor
Definition at line 67 of file stabilizer.h.
Referenced by stabilizer_loop().
#define K_ANGLE 5.0
tilt angle factor for kalman algorithm TODO: add detailed description here! This is not documented in original code
Definition at line 86 of file stabilizer.h.
Referenced by stabilizer_loop().
#define K_CORR_FACTOR 1.0
correction factor for kalman algorithm TODO: add detailed description here! This is not documented in original code
Definition at line 96 of file stabilizer.h.
#define K_OMEGA 0.16666
angular speed (omega) factor for kalman algorithm TODO: add detailed description here! This is not documented in original code
Definition at line 91 of file stabilizer.h.
Referenced by stabilizer_loop().
#define PI 3.14
PI ...
Definition at line 52 of file stabilizer.h.
Referenced by stabilizer_loop().
#define SET_POINT 0.0
setpoint (sollwert) of the controlling algorithm TODO: Check comment! Add detailed desciption
Definition at line 100 of file stabilizer.h.
Referenced by stabilizer_loop().
#define STEERING_RESPONSIVENESS 0.001
Definition at line 81 of file stabilizer.h.
Referenced by stabilizer_loop().
#define STEERING_ZERO_POINT 512
zero point of the steering potentiometer. (10Bit resolution -> 1024 max, so 1024/2)
Definition at line 78 of file stabilizer.h.
Referenced by stabilizer_loop().
Function Documentation
void stabilizer_loop (void)
Definition at line 45 of file stabilizer.c.
References accl_high_samples, accl_low_samples, ACCL_SAMPLES_BUFSIZE, ACCL_TO_DEGREE_FACTOR, adc_sel_channel(), ADC_STEERING_1, CUR_SPEED_FACTOR, gyro1_samples, GYRO1_SAMPLES_BUFSIZE, GYRO1_ZERO_VALUE, GYRO_TO_OMEGA_FACTOR, K_ANGLE, K_OMEGA, PI, PWM_RESOLUTION, read_adc(), set_motor1(), set_motor2(), SET_POINT, STEERING_RESPONSIVENESS, STEERING_ZERO_POINT, and uart_puts().