stabilizer.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include `globals.h`
#include `stabilizer.h`
#include `adc.h`
#include `motor_pwm.h`
Functions
void stabilizer_loop (void)
Function Documentation
void stabilizer_loop (void)
Definition at line 45 of file stabilizer.c.
References accl_high_samples, accl_low_samples, ACCL_SAMPLES_BUFSIZE, ACCL_TO_DEGREE_FACTOR, adc_sel_channel(), ADC_STEERING_1, CUR_SPEED_FACTOR, gyro1_samples, GYRO1_SAMPLES_BUFSIZE, GYRO1_ZERO_VALUE, GYRO_TO_OMEGA_FACTOR, K_ANGLE, K_OMEGA, PI, PWM_RESOLUTION, read_adc(), set_motor1(), set_motor2(), SET_POINT, STEERING_RESPONSIVENESS, STEERING_ZERO_POINT, and uart_puts().